import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
    console.log('🌱 Iniciando seed...\n');

// ============================================================
// 1. TABELAS AUXILIARES (referências)
// ============================================================

    console.log('➡️ Inserindo Companhias...');
    await prisma.companhia.createMany({
        data: [
        { id: 1, nome: 'Transporte A' },
        { id: 2, nome: 'Logistica B' },
        { id: 3, nome: 'Frota Exemplo' },
        ],
        skipDuplicates: true
    });

    console.log('➡️ Inserindo Marcas...');
    await prisma.marca.createMany({
        data: [
        { id: 1, nome: 'Fiat' },
        { id: 2, nome: 'Volkswagen' },
        { id: 3, nome: 'Toyota' },
        { id: 4, nome: 'Chevrolet' },
        { id: 5, nome: 'Ford' },
        { id: 6, nome: 'Renault' },
        ],
        skipDuplicates: true
    });

    console.log('➡️ Inserindo Categorias...');
    await prisma.categoria.createMany({
        data: [
        { id: 1, nome: 'Carro' },
        { id: 2, nome: 'Van' },
        { id: 3, nome: 'Ônibus' },
        { id: 4, nome: 'Caminhão' },
        ],
        skipDuplicates: true
    });

    console.log('➡️ Inserindo Classificações...');
    await prisma.classificacao.createMany({
        data: [
        { id: 1, nome: 'Basic' },
        { id: 2, nome: 'Premium' },
        { id: 3, nome: 'Executiva' },
        ],
        skipDuplicates: true
    });

    console.log('➡️ Inserindo Tipos de Placa...');
    await prisma.tipo_placa.createMany({
        data: [
        { id: 1, nome: 'Comum' },
        { id: 2, nome: 'Mercosul' },
        { id: 3, nome: 'Especial' },
        ],
        skipDuplicates: true
    });

    console.log('➡️ Inserindo Combustíveis...');
    await prisma.combustivel.createMany({
        data: [
        { id: 1, nome: 'Gasolina' },
        { id: 2, nome: 'Etanol' },
        { id: 3, nome: 'Diesel' },
        { id: 4, nome: 'Flex' },
        ],
        skipDuplicates: true
    });

    console.log('➡️ Inserindo Tipo de Ocorrência...');
    await prisma.tipo_ocorrencia.createMany({
        data: [
        { id: 1, nome: 'Acidente' },
        { id: 2, nome: 'Roubo' },
        { id: 3, nome: 'Quebra mecânica' },
        { id: 4, nome: 'Multa' },
        ],
        skipDuplicates: true
    });

    console.log('➡️ Inserindo Seriedade de Ocorrência...');
    await prisma.seriedade_ocorrencia.createMany({
        data: [
        { id: 1, nome: 'Baixa' },
        { id: 2, nome: 'Média' },
        { id: 3, nome: 'Alta' },
        ],
        skipDuplicates: true
    });

    console.log('➡️ Inserindo Usuários...');
    await prisma.usuario.createMany({
        data: [
        { id: 1, nome: 'Administrador', email: 'admin@sistema.com' },
        { id: 2, nome: 'Operador 1', email: 'operador1@sistema.com' },
        { id: 3, nome: 'Operador 2', email: 'operador2@sistema.com' },
        ],
        skipDuplicates: true
    });

    console.log('✔️ Parte 1 concluída.\n');

  //
  // ============================================================
  // 3. VEÍCULOS (Parte 1)
  // ============================================================
  //

  console.log('➡️ Inserindo Veículos 1 a 10...');

  await prisma.veiculo.create({
    data: {
      id: 1,
      criado_em: new Date(),
      identificador: "UNO-001",
      companhia_id: 1,
      status: "liberado",
      modelo: "Uno Mille",
      ano: 2010,
      marca_id: 1,
      categoria_id: 1,
      classificacao_id: 1,
      capacidade: 5,
      portais: 2,
      estado: "SP",
      uf: "SP",
      tipo_placa_id: 2,
      placa: "ABC1D23",
      renavam: "12345678901",
      chassi: "9BWZZZ377VT004251",
      revisao_km: 150000,
      combustivel_id: 4,
      descricao: "Veículo em bom estado.",
      usuario_id: 1
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 2,
      criado_em: new Date(),
      identificador: "GOL-001",
      companhia_id: 1,
      status: "liberado",
      modelo: "Gol G5",
      ano: 2012,
      marca_id: 2,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: "RJ",
      uf: "RJ",
      tipo_placa_id: 2,
      placa: "XYZ2F45",
      renavam: "98765432100",
      chassi: "9BWZZZ377VT004300",
      revisao_km: 130000,
      combustivel_id: 4,
      descricao: "Uso urbano.",
      usuario_id: 1
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 3,
      criado_em: new Date(),
      identificador: "STR-100",
      companhia_id: 2,
      status: "pendente",
      modelo: "Strada Working",
      ano: 2015,
      marca_id: 1,
      categoria_id: 1,
      classificacao_id: 1,
      capacidade: 2,
      portais: 2,
      estado: "MG",
      uf: "MG",
      tipo_placa_id: 1,
      placa: "HJK-8899",
      renavam: "56473829100",
      chassi: "9BWZZZ377VT009900",
      revisao_km: 90000,
      combustivel_id: 4,
      descricao: "Veículo de carga leve.",
      usuario_id: 2
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 4,
      criado_em: new Date(),
      identificador: "HILUX-01",
      companhia_id: 2,
      status: "liberado",
      modelo: "Hilux SRV",
      ano: 2020,
      marca_id: 3,
      categoria_id: 3,
      classificacao_id: 2,
      capacidade: 5,
      portais: 4,
      estado: "PR",
      uf: "PR",
      tipo_placa_id: 2,
      placa: "QWE3H67",
      renavam: "22233344455",
      chassi: "9BWZZZ377VT007700",
      revisao_km: 40000,
      combustivel_id: 3,
      descricao: "Veículo 4x4.",
      usuario_id: 2
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 5,
      criado_em: new Date(),
      identificador: "KA-778",
      companhia_id: 1,
      status: "liberado",
      modelo: "Ford Ka",
      ano: 2018,
      marca_id: 5,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: "SC",
      uf: "SC",
      tipo_placa_id: 2,
      placa: "KLM9P88",
      renavam: "44556677889",
      chassi: "9BWZZZ377VT005500",
      revisao_km: 70000,
      combustivel_id: 4,
      descricao: "Veículo econômico.",
      usuario_id: 1
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 6,
      criado_em: new Date(),
      identificador: "LOGAN-55",
      companhia_id: 1,
      status: "liberado",
      modelo: "Renault Logan",
      ano: 2017,
      marca_id: 6,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: "BA",
      uf: "BA",
      tipo_placa_id: 2,
      placa: "BCA5V66",
      renavam: "11223344556",
      chassi: "9BWZZZ377VT003344",
      revisao_km: 95000,
      combustivel_id: 4,
      descricao: "Veículo de frota.",
      usuario_id: 3
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 7,
      criado_em: new Date(),
      identificador: "CIVIC-20",
      companhia_id: 2,
      status: "liberado",
      modelo: "Honda Civic",
      ano: 2019,
      marca_id: 4,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: "RS",
      uf: "RS",
      tipo_placa_id: 2,
      placa: "UIO7N12",
      renavam: "99887766554",
      chassi: "9BWZZZ377VT001122",
      revisao_km: 50000,
      combustivel_id: 4,
      descricao: "Sedan confortável.",
      usuario_id: 2
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 8,
      criado_em: new Date(),
      identificador: "S10-900",
      companhia_id: 1,
      status: "liberado",
      modelo: "S10 LT",
      ano: 2016,
      marca_id: 4,
      categoria_id: 4,
      classificacao_id: 3,
      capacidade: 3,
      portais: 2,
      estado: "GO",
      uf: "GO",
      tipo_placa_id: 2,
      placa: "OPQ4L55",
      renavam: "66778899001",
      chassi: "9BWZZZ377VT008811",
      revisao_km: 120000,
      combustivel_id: 3,
      descricao: "Caminhonete diesel.",
      usuario_id: 1
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 9,
      criado_em: new Date(),
      identificador: "UNO-001-9", // corrigido por duplicação
      companhia_id: 1,
      status: "liberado",
      modelo: "Uno Mille",
      ano: 2010,
      marca_id: 1,
      categoria_id: 1,
      classificacao_id: 1,
      capacidade: 5,
      portais: 2,
      estado: "SP",
      uf: "SP",
      tipo_placa_id: 2,
      placa: "ABC1D24", // gerado automaticamente
      renavam: "12345678902", // incrementado
      chassi: "9BWZZZ377VT004252", // último dígito alterado
      revisao_km: 150000,
      combustivel_id: 4,
      descricao: "Segundo registro corrigido.",
      usuario_id: 1
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 10,
      criado_em: new Date(),
      identificador: "GOL-001-10", // corrigido por duplicação
      companhia_id: 1,
      status: "liberado",
      modelo: "Gol G5",
      ano: 2012,
      marca_id: 2,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: "RJ",
      uf: "RJ",
      tipo_placa_id: 2,
      placa: "XYZ2F46", // gerado
      renavam: "98765432101", // incrementado
      chassi: "9BWZZZ377VT004301", // último dígito alterado
      revisao_km: 130000,
      combustivel_id: 4,
      descricao: "Duplicado corrigido.",
      usuario_id: 1
    }
  });

    console.log('➡️ Inserindo Veículos 11 a 20...');

  await prisma.veiculo.create({
    data: {
      id: 11,
      criado_em: new Date(),
      identificador: "HILUX-01-11", // duplicado corrigido
      companhia_id: 2,
      status: "liberado",
      modelo: "Hilux SRV",
      ano: 2020,
      marca_id: 3,
      categoria_id: 3,
      classificacao_id: 2,
      capacidade: 5,
      portais: 4,
      estado: "PR",
      uf: "PR",
      tipo_placa_id: 2,
      placa: "QWE3H68",  // placa gerada
      renavam: "22233344456",
      chassi: "9BWZZZ377VT007701", // chassi ajustado
      revisao_km: 40000,
      combustivel_id: 3,
      descricao: "Duplicado corrigido.",
      usuario_id: 2
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 12,
      criado_em: new Date(),
      identificador: "ONIX-500",
      companhia_id: 1,
      status: "liberado",
      modelo: "Onix LT",
      ano: 2021,
      marca_id: 4,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: "SP",
      uf: "SP",
      tipo_placa_id: 2,
      placa: "RTY8M22",
      renavam: "32165498700",
      chassi: "9BWZZZ377VT006644",
      revisao_km: 30000,
      combustivel_id: 4,
      descricao: "Veículo novo na frota.",
      usuario_id: 3
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 13,
      criado_em: new Date(),
      identificador: "RENE-200",
      companhia_id: 2,
      status: "liberado",
      modelo: "Renegade Sport",
      ano: 2019,
      marca_id: 6,
      categoria_id: 3,
      classificacao_id: 2,
      capacidade: 5,
      portais: 4,
      estado: "RS",
      uf: "RS",
      tipo_placa_id: 2,
      placa: "FGH2B90",
      renavam: "77788899911",
      chassi: "9BWZZZ377VT002233",
      revisao_km: 60000,
      combustivel_id: 4,
      descricao: "SUV utilizado em rotas mistas.",
      usuario_id: 1
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 14,
      criado_em: new Date(),
      identificador: "MASTER-77",
      companhia_id: 1,
      status: "liberado",
      modelo: "Renault Master",
      ano: 2018,
      marca_id: 6,
      categoria_id: 4,
      classificacao_id: 3,
      capacidade: 16,
      portais: 3,
      estado: "GO",
      uf: "GO",
      tipo_placa_id: 2,
      placa: "PLM3H21",
      renavam: "99884455221",
      chassi: "9BWZZZ377VT001188",
      revisao_km: 140000,
      combustivel_id: 3,
      descricao: "Van para transporte.",
      usuario_id: 1
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 15,
      criado_em: new Date(),
      identificador: "F250-900",
      companhia_id: 2,
      status: "liberado",
      modelo: "F-250 XLT",
      ano: 2010,
      marca_id: 5,
      categoria_id: 4,
      classificacao_id: 3,
      capacidade: 3,
      portais: 2,
      estado: "MS",
      uf: "MS",
      tipo_placa_id: 1,
      placa: "JJK-4455",
      renavam: "55119988442",
      chassi: "9BWZZZ377VT004111",
      revisao_km: 210000,
      combustivel_id: 3,
      descricao: "Caminhonete robusta.",
      usuario_id: 3
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 16,
      criado_em: new Date(),
      identificador: "KA-778-16", // duplicado corrigido
      companhia_id: 1,
      status: "liberado",
      modelo: "Ford Ka",
      ano: 2018,
      marca_id: 5,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: "SC",
      uf: "SC",
      tipo_placa_id: 2,
      placa: "KLM9P89", // nova
      renavam: "44556677890",
      chassi: "9BWZZZ377VT005501", // ajustado
      revisao_km: 70000,
      combustivel_id: 4,
      descricao: "Registro duplicado corrigido.",
      usuario_id: 1
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 17,
      criado_em: new Date(),
      identificador: "RANGER-12",
      companhia_id: 2,
      status: "liberado",
      modelo: "Ford Ranger",
      ano: 2017,
      marca_id: 5,
      categoria_id: 4,
      classificacao_id: 3,
      capacidade: 5,
      portais: 4,
      estado: "PA",
      uf: "PA",
      tipo_placa_id: 2,
      placa: "ASD4K88",
      renavam: "11002200334",
      chassi: "9BWZZZ377VT009100",
      revisao_km: 160000,
      combustivel_id: 3,
      descricao: "Caminhonete diesel 4x4.",
      usuario_id: 1
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 18,
      criado_em: new Date(),
      identificador: "COROLLA-22",
      companhia_id: 1,
      status: "liberado",
      modelo: "Corolla GLI",
      ano: 2019,
      marca_id: 3,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: "SP",
      uf: "SP",
      tipo_placa_id: 2,
      placa: "GHJ9K22",
      renavam: "44553322441",
      chassi: "9BWZZZ377VT007788",
      revisao_km: 45000,
      combustivel_id: 4,
      descricao: "Sedan premium.",
      usuario_id: 1
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 19,
      criado_em: new Date(),
      identificador: "LOGAN-55-19", // duplicado corrigido
      companhia_id: 1,
      status: "liberado",
      modelo: "Renault Logan",
      ano: 2017,
      marca_id: 6,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: "BA",
      uf: "BA",
      tipo_placa_id: 2,
      placa: "BCA5V67", // nova
      renavam: "11223344557",
      chassi: "9BWZZZ377VT003345",
      revisao_km: 95000,
      combustivel_id: 4,
      descricao: "Duplicado corrigido.",
      usuario_id: 3
    }
  });

  await prisma.veiculo.create({
    data: {
      id: 20,
      criado_em: new Date(),
      identificador: "CORSA-88",
      companhia_id: 1,
      status: "pendente",
      modelo: "Corsa Sedan",
      ano: 2008,
      marca_id: 4,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: "RJ",
      uf: "RJ",
      tipo_placa_id: 1,
      placa: "RTT-9022",
      renavam: "22446688110",
      chassi: "9BWZZZ377VT000800",
      revisao_km: 180000,
      combustivel_id: 4,
      descricao: "Veículo antigo porém funcional.",
      usuario_id: 2
    }
  });

    //
  // ============================================================
  // 3. VEÍCULOS (continuação)
  // ============================================================
  //

  console.log('➡️ Inserindo Veículos 21 a 30...');

  await prisma.veiculo.createMany({
    data: [
      {
        id: 21,
        criado_em: new Date(),
        identificador: 'VEI-021',
        companhia_id: 1,
        status: 'pendente',
        modelo: 'Onix LT',
        ano: 2019,
        marca_id: 4,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 2,
        estado: 'São Paulo',
        uf: 'SP',
        tipo_placa_id: 2,
        placa: 'ABC2A21',
        renavam: '00210000021',
        chassi: '9BWZZZ21ZXT021021',
        revisao_km: 35000,
        combustivel_id: 4,
        descricao: 'Veículo compacto para equipe administrativa.',
        usuario_id: 2,
      },
      {
        id: 22,
        criado_em: new Date(),
        identificador: 'VEI-022',
        companhia_id: 2,
        status: 'liberado',
        modelo: 'Ranger XLS',
        ano: 2022,
        marca_id: 5,
        categoria_id: 4,
        classificacao_id: 3,
        capacidade: 5,
        portais: 4,
        estado: 'Goiás',
        uf: 'GO',
        tipo_placa_id: 2,
        placa: 'GHI2B22',
        renavam: '00220000022',
        chassi: '9BWZZZ22ZXT022022',
        revisao_km: 15000,
        combustivel_id: 3,
        descricao: 'Caminhonete utilizada no transporte pesado.',
        usuario_id: 1,
      },
      {
        id: 23,
        criado_em: new Date(),
        identificador: 'VEI-023',
        companhia_id: 1,
        status: 'pendente',
        modelo: 'Corolla XEi',
        ano: 2020,
        marca_id: 3,
        categoria_id: 3,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Bahia',
        uf: 'BA',
        tipo_placa_id: 2,
        placa: 'JKL2C23',
        renavam: '00230000023',
        chassi: '9BWZZZ23ZXT023023',
        revisao_km: 28000,
        combustivel_id: 4,
        descricao: 'Sedan confortável para viagem corporativa.',
        usuario_id: 3,
      },
      {
        id: 24,
        criado_em: new Date(),
        identificador: 'VEI-024',
        companhia_id: 2,
        status: 'cancelado',
        modelo: 'Sandero Expression',
        ano: 2018,
        marca_id: 6,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Paraná',
        uf: 'PR',
        tipo_placa_id: 1,
        placa: 'MNO2D24',
        renavam: '00240000024',
        chassi: '9BWZZZ24ZXT024024',
        revisao_km: 45000,
        combustivel_id: 2,
        descricao: 'Veículo retirado de operação após sinistro.',
        usuario_id: 1,
      },
      {
        id: 25,
        criado_em: new Date(),
        identificador: 'VEI-025',
        companhia_id: 1,
        status: 'liberado',
        modelo: 'Duster Iconic',
        ano: 2021,
        marca_id: 6,
        categoria_id: 3,
        classificacao_id: 2,
        capacidade: 5,
        portais: 4,
        estado: 'Mato Grosso',
        uf: 'MT',
        tipo_placa_id: 2,
        placa: 'PQR2E25',
        renavam: '00250000025',
        chassi: '9BWZZZ25ZXT025025',
        revisao_km: 12000,
        combustivel_id: 4,
        descricao: 'SUV utilizado por gestores regionais.',
        usuario_id: 2,
      },
      {
        id: 26,
        criado_em: new Date(),
        identificador: 'VEI-026',
        companhia_id: 2,
        status: 'pendente',
        modelo: 'Hilux SRV',
        ano: 2022,
        marca_id: 3,
        categoria_id: 4,
        classificacao_id: 3,
        capacidade: 5,
        portais: 4,
        estado: 'Tocantins',
        uf: 'TO',
        tipo_placa_id: 2,
        placa: 'STU2F26',
        renavam: '00260000026',
        chassi: '9BWZZZ26ZXT026026',
        revisao_km: 10000,
        combustivel_id: 3,
        descricao: 'Utilizada em rotas rurais de difícil acesso.',
        usuario_id: 3,
      },
      {
        id: 27,
        criado_em: new Date(),
        identificador: 'VEI-027',
        companhia_id: 1,
        status: 'liberado',
        modelo: 'Gol G6',
        ano: 2017,
        marca_id: 2,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Pernambuco',
        uf: 'PE',
        tipo_placa_id: 1,
        placa: 'VWX2G27',
        renavam: '00270000027',
        chassi: '9BWZZZ27ZXT027027',
        revisao_km: 52000,
        combustivel_id: 1,
        descricao: 'Modelo antigo ainda em atividade.',
        usuario_id: 1,
      },
      {
        id: 28,
        criado_em: new Date(),
        identificador: 'VEI-028',
        companhia_id: 2,
        status: 'cancelado',
        modelo: 'Strada Working',
        ano: 2016,
        marca_id: 1,
        categoria_id: 1,
        classificacao_id: 2,
        capacidade: 2,
        portais: 2,
        estado: 'Sergipe',
        uf: 'SE',
        tipo_placa_id: 1,
        placa: 'YZA2H28',
        renavam: '00280000028',
        chassi: '9BWZZZ28ZXT028028',
        revisao_km: 70000,
        combustivel_id: 1,
        descricao: 'Veículo desativado por desgaste extremo.',
        usuario_id: 2,
      },
      {
        id: 29,
        criado_em: new Date(),
        identificador: 'VEI-029',
        companhia_id: 1,
        status: 'pendente',
        modelo: 'Cruze LTZ',
        ano: 2020,
        marca_id: 4,
        categoria_id: 3,
        classificacao_id: 2,
        capacidade: 5,
        portais: 4,
        estado: 'Rio Grande do Norte',
        uf: 'RN',
        tipo_placa_id: 2,
        placa: 'BCD2I29',
        renavam: '00290000029',
        chassi: '9BWZZZ29ZXT029029',
        revisao_km: 26000,
        combustivel_id: 4,
        descricao: 'Sedan premium para supervisores.',
        usuario_id: 3,
      },
      {
        id: 30,
        criado_em: new Date(),
        identificador: 'VEI-030',
        companhia_id: 2,
        status: 'liberado',
        modelo: 'Ka SE',
        ano: 2019,
        marca_id: 5,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Amapá',
        uf: 'AP',
        tipo_placa_id: 2,
        placa: 'EFG2J30',
        renavam: '00300000030',
        chassi: '9BWZZZ30ZXT030030',
        revisao_km: 33000,
        combustivel_id: 2,
        descricao: 'Utilizado por equipe de logística leve.',
        usuario_id: 1,
      },
    ],
    skipDuplicates: true
  });

  console.log('✔️ Veículos 21–30 incluídos.\n');

    console.log('➡️ Inserindo Veículos 31 a 40...');

  await prisma.veiculo.createMany({
    data: [
      {
        id: 31,
        criado_em: new Date(),
        identificador: 'VEI-031',
        companhia_id: 1,
        status: 'pendente',
        modelo: 'Logan Authentique',
        ano: 2018,
        marca_id: 6,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Acre',
        uf: 'AC',
        tipo_placa_id: 1,
        placa: 'ACD3A31',
        renavam: '00310000031',
        chassi: '9BWZZZ31ZXT031031',
        revisao_km: 44000,
        combustivel_id: 1,
        descricao: 'Veículo para uso de entregas rápidas.',
        usuario_id: 3,
      },
      {
        id: 32,
        criado_em: new Date(),
        identificador: 'VEI-032',
        companhia_id: 2,
        status: 'liberado',
        modelo: 'Toro Freedom',
        ano: 2021,
        marca_id: 1,
        categoria_id: 4,
        classificacao_id: 2,
        capacidade: 5,
        portais: 4,
        estado: 'Rondônia',
        uf: 'RO',
        tipo_placa_id: 2,
        placa: 'BDE3B32',
        renavam: '00320000032',
        chassi: '9BWZZZ32ZXT032032',
        revisao_km: 18000,
        combustivel_id: 3,
        descricao: 'Picape utilitária para transporte médio.',
        usuario_id: 1,
      },
      {
        id: 33,
        criado_em: new Date(),
        identificador: 'VEI-033',
        companhia_id: 1,
        status: 'cancelado',
        modelo: 'HB20 Vision',
        ano: 2019,
        marca_id: 2,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Roraima',
        uf: 'RR',
        tipo_placa_id: 2,
        placa: 'CDF3C33',
        renavam: '00330000033',
        chassi: '9BWZZZ33ZXT033033',
        revisao_km: 39000,
        combustivel_id: 2,
        descricao: 'Desativado por colisão frontal.',
        usuario_id: 2,
      },
      {
        id: 34,
        criado_em: new Date(),
        identificador: 'VEI-034',
        companhia_id: 2,
        status: 'pendente',
        modelo: 'S10 LT',
        ano: 2022,
        marca_id: 4,
        categoria_id: 4,
        classificacao_id: 3,
        capacidade: 5,
        portais: 4,
        estado: 'Ceará',
        uf: 'CE',
        tipo_placa_id: 2,
        placa: 'EFG3D34',
        renavam: '00340000034',
        chassi: '9BWZZZ34ZXT034034',
        revisao_km: 11000,
        combustivel_id: 3,
        descricao: 'Veículo utilizado em operações de campo intensas.',
        usuario_id: 1,
      },
      {
        id: 35,
        criado_em: new Date(),
        identificador: 'VEI-035',
        companhia_id: 1,
        status: 'liberado',
        modelo: 'Kwid Zen',
        ano: 2020,
        marca_id: 6,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Paraíba',
        uf: 'PB',
        tipo_placa_id: 2,
        placa: 'FGH3E35',
        renavam: '00350000035',
        chassi: '9BWZZZ35ZXT035035',
        revisao_km: 24000,
        combustivel_id: 1,
        descricao: 'Modelo econômico para deslocamentos urbanos.',
        usuario_id: 3,
      },
      {
        id: 36,
        criado_em: new Date(),
        identificador: 'VEI-036',
        companhia_id: 2,
        status: 'pendente',
        modelo: 'Amarok Highline',
        ano: 2021,
        marca_id: 2,
        categoria_id: 4,
        classificacao_id: 3,
        capacidade: 5,
        portais: 4,
        estado: 'Piauí',
        uf: 'PI',
        tipo_placa_id: 2,
        placa: 'GHI3F36',
        renavam: '00360000036',
        chassi: '9BWZZZ36ZXT036036',
        revisao_km: 17000,
        combustivel_id: 3,
        descricao: 'Caminhonete para inspeções e auditorias externas.',
        usuario_id: 2,
      },
      {
        id: 37,
        criado_em: new Date(),
        identificador: 'VEI-037',
        companhia_id: 1,
        status: 'cancelado',
        modelo: 'Ka Sedan SE',
        ano: 2018,
        marca_id: 5,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Rio Grande do Sul',
        uf: 'RS',
        tipo_placa_id: 1,
        placa: 'HIJ3G37',
        renavam: '00370000037',
        chassi: '9BWZZZ37ZXT037037',
        revisao_km: 58000,
        combustivel_id: 1,
        descricao: 'Desativado após problemas mecânicos graves.',
        usuario_id: 1,
      },
      {
        id: 38,
        criado_em: new Date(),
        identificador: 'VEI-038',
        companhia_id: 2,
        status: 'liberado',
        modelo: 'EcoSport Freestyle',
        ano: 2019,
        marca_id: 5,
        categoria_id: 3,
        classificacao_id: 2,
        capacidade: 5,
        portais: 4,
        estado: 'Distrito Federal',
        uf: 'DF',
        tipo_placa_id: 2,
        placa: 'JKL3H38',
        renavam: '00380000038',
        chassi: '9BWZZZ38ZXT038038',
        revisao_km: 29000,
        combustivel_id: 4,
        descricao: 'SUV para mobilidade regional de supervisores.',
        usuario_id: 2,
      },
      {
        id: 39,
        criado_em: new Date(),
        identificador: 'VEI-039',
        companhia_id: 1,
        status: 'pendente',
        modelo: 'Celta LS',
        ano: 2016,
        marca_id: 4,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Amazonas',
        uf: 'AM',
        tipo_placa_id: 1,
        placa: 'LMN3I39',
        renavam: '00390000039',
        chassi: '9BWZZZ39ZXT039039',
        revisao_km: 72000,
        combustivel_id: 1,
        descricao: 'Veículo mais antigo em uso, destinado a tarefas leves.',
        usuario_id: 3,
      },
      {
        id: 40,
        criado_em: new Date(),
        identificador: 'VEI-040',
        companhia_id: 2,
        status: 'liberado',
        modelo: 'Yaris XLS',
        ano: 2021,
        marca_id: 3,
        categoria_id: 3,
        classificacao_id: 2,
        capacidade: 5,
        portais: 4,
        estado: 'Pará',
        uf: 'PA',
        tipo_placa_id: 2,
        placa: 'NOP3J40',
        renavam: '00400000040',
        chassi: '9BWZZZ40ZXT040040',
        revisao_km: 21000,
        combustivel_id: 4,
        descricao: 'Hatch premium utilizado pela gerência.',
        usuario_id: 1,
      },
    ],
    skipDuplicates: true
  });

  console.log('✔️ Veículos 31–40 incluídos.\n');

    console.log('➡️ Inserindo Veículos 41 a 50...');

  await prisma.veiculo.createMany({
    data: [
      {
        id: 41,
        criado_em: new Date(),
        identificador: 'VEI-041',
        companhia_id: 1,
        status: 'liberado',
        modelo: 'Palio Fire',
        ano: 2015,
        marca_id: 1,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Santa Catarina',
        uf: 'SC',
        tipo_placa_id: 1,
        placa: 'ABC4A41',
        renavam: '00410000041',
        chassi: '9BWZZZ41ZXT041041',
        revisao_km: 82000,
        combustivel_id: 1,
        descricao: 'Carro simples para serviços de rua.',
        usuario_id: 3,
      },
      {
        id: 42,
        criado_em: new Date(),
        identificador: 'VEI-042',
        companhia_id: 2,
        status: 'pendente',
        modelo: 'Civic Touring',
        ano: 2020,
        marca_id: 3,
        categoria_id: 3,
        classificacao_id: 2,
        capacidade: 5,
        portais: 4,
        estado: 'Minas Gerais',
        uf: 'MG',
        tipo_placa_id: 2,
        placa: 'BCD4B42',
        renavam: '00420000042',
        chassi: '9BWZZZ42ZXT042042',
        revisao_km: 25000,
        combustivel_id: 4,
        descricao: 'Sedan executivo usado pela diretoria.',
        usuario_id: 1,
      },
      {
        id: 43,
        criado_em: new Date(),
        identificador: 'VEI-043',
        companhia_id: 1,
        status: 'pendente',
        modelo: 'Saveiro Robust',
        ano: 2021,
        marca_id: 2,
        categoria_id: 4,
        classificacao_id: 2,
        capacidade: 2,
        portais: 2,
        estado: 'Espírito Santo',
        uf: 'ES',
        tipo_placa_id: 2,
        placa: 'CDE4C43',
        renavam: '00430000043',
        chassi: '9BWZZZ43ZXT043043',
        revisao_km: 17000,
        combustivel_id: 1,
        descricao: 'Veículo de apoio para transporte leve.',
        usuario_id: 2,
      },
      {
        id: 44,
        criado_em: new Date(),
        identificador: 'VEI-044',
        companhia_id: 2,
        status: 'liberado',
        modelo: 'Fiesta SE',
        ano: 2017,
        marca_id: 5,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Maranhão',
        uf: 'MA',
        tipo_placa_id: 1,
        placa: 'DEF4D44',
        renavam: '00440000044',
        chassi: '9BWZZZ44ZXT044044',
        revisao_km: 49000,
        combustivel_id: 2,
        descricao: 'Carro intermediário utilizado por analistas.',
        usuario_id: 1,
      },
      {
        id: 45,
        criado_em: new Date(),
        identificador: 'VEI-045',
        companhia_id: 1,
        status: 'cancelado',
        modelo: 'Etios X',
        ano: 2018,
        marca_id: 3,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Alagoas',
        uf: 'AL',
        tipo_placa_id: 1,
        placa: 'EFG4E45',
        renavam: '00450000045',
        chassi: '9BWZZZ45ZXT045045',
        revisao_km: 61000,
        combustivel_id: 1,
        descricao: 'Veículo retirado por falhas persistentes no motor.',
        usuario_id: 2,
      },
      {
        id: 46,
        criado_em: new Date(),
        identificador: 'VEI-046',
        companhia_id: 2,
        status: 'pendente',
        modelo: 'Siena EL',
        ano: 2016,
        marca_id: 1,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Bahia',
        uf: 'BA',
        tipo_placa_id: 1,
        placa: 'FGH4F46',
        renavam: '00460000046',
        chassi: '9BWZZZ46ZXT046046',
        revisao_km: 76000,
        combustivel_id: 1,
        descricao: 'Ambulatório externo e visitas programadas.',
        usuario_id: 3,
      },
      {
        id: 47,
        criado_em: new Date(),
        identificador: 'VEI-047',
        companhia_id: 1,
        status: 'liberado',
        modelo: 'Compass Longitude',
        ano: 2021,
        marca_id: 4,
        categoria_id: 3,
        classificacao_id: 2,
        capacidade: 5,
        portais: 4,
        estado: 'Amazonas',
        uf: 'AM',
        tipo_placa_id: 2,
        placa: 'GHI4G47',
        renavam: '00470000047',
        chassi: '9BWZZZ47ZXT047047',
        revisao_km: 22000,
        combustivel_id: 4,
        descricao: 'SUV premium utilizado por gestores corporativos.',
        usuario_id: 1,
      },
      {
        id: 48,
        criado_em: new Date(),
        identificador: 'VEI-048',
        companhia_id: 2,
        status: 'pendente',
        modelo: 'Fiorino Hard Working',
        ano: 2019,
        marca_id: 1,
        categoria_id: 1,
        classificacao_id: 2,
        capacidade: 2,
        portais: 3,
        estado: 'São Paulo',
        uf: 'SP',
        tipo_placa_id: 2,
        placa: 'HIJ4H48',
        renavam: '00480000048',
        chassi: '9BWZZZ48ZXT048048',
        revisao_km: 34000,
        combustivel_id: 1,
        descricao: 'Utilitário compacto para entregas rápidas.',
        usuario_id: 2,
      },
      {
        id: 49,
        criado_em: new Date(),
        identificador: 'VEI-049',
        companhia_id: 1,
        status: 'liberado',
        modelo: 'Corolla GLi',
        ano: 2017,
        marca_id: 3,
        categoria_id: 3,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Ceará',
        uf: 'CE',
        tipo_placa_id: 1,
        placa: 'JKL4I49',
        renavam: '00490000049',
        chassi: '9BWZZZ49ZXT049049',
        revisao_km: 58000,
        combustivel_id: 4,
        descricao: 'Sedan usado para viagens regionais.',
        usuario_id: 3,
      },
      {
        id: 50,
        criado_em: new Date(),
        identificador: 'VEI-050',
        companhia_id: 2,
        status: 'pendente',
        modelo: 'Uno Attractive',
        ano: 2018,
        marca_id: 1,
        categoria_id: 2,
        classificacao_id: 1,
        capacidade: 5,
        portais: 4,
        estado: 'Pernambuco',
        uf: 'PE',
        tipo_placa_id: 2,
        placa: 'LMN4J50',
        renavam: '00500000050',
        chassi: '9BWZZZ50ZXT050050',
        revisao_km: 42000,
        combustivel_id: 2,
        descricao: 'Veículo compacto para serviços administrativos.',
        usuario_id: 1,
      },
    ],
    skipDuplicates: true
  });

  console.log('✔️ Veículos 41–50 incluídos.\n');

  console.log('➡️ Inserindo Veículos 51 a 60...');

await prisma.veiculo.createMany({
  data: [
    {
      id: 51,
      criado_em: new Date(),
      identificador: 'VEI-051',
      companhia_id: 1,
      status: 'pendente',
      modelo: 'Voyage Trend',
      ano: 2019,
      marca_id: 2,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: 'Pará',
      uf: 'PA',
      tipo_placa_id: 1,
      placa: 'ABC5A51',
      renavam: '00510000051',
      chassi: '9BWZZZ51ZXT051051',
      revisao_km: 38000,
      combustivel_id: 4,
      descricao: 'Sedan compacto para transporte de equipe.',
      usuario_id: 3,
    },
    {
      id: 52,
      criado_em: new Date(),
      identificador: 'VEI-052',
      companhia_id: 2,
      status: 'liberado',
      modelo: 'Celta Life',
      ano: 2014,
      marca_id: 5,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: 'Rio Grande do Norte',
      uf: 'RN',
      tipo_placa_id: 1,
      placa: 'BCD5B52',
      renavam: '00520000052',
      chassi: '9BWZZZ52ZXT052052',
      revisao_km: 92000,
      combustivel_id: 1,
      descricao: 'Utilizado para rotinas básicas de entrega.',
      usuario_id: 1,
    },
    {
      id: 53,
      criado_em: new Date(),
      identificador: 'VEI-053',
      companhia_id: 1,
      status: 'cancelado',
      modelo: 'Onix LT',
      ano: 2020,
      marca_id: 5,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: 'Paraíba',
      uf: 'PB',
      tipo_placa_id: 2,
      placa: 'CDE5C53',
      renavam: '00530000053',
      chassi: '9BWZZZ53ZXT053053',
      revisao_km: 21000,
      combustivel_id: 4,
      descricao: 'Cancelado após colisão frontal leve.',
      usuario_id: 2,
    },
    {
      id: 54,
      criado_em: new Date(),
      identificador: 'VEI-054',
      companhia_id: 2,
      status: 'liberado',
      modelo: 'HR-V EX',
      ano: 2021,
      marca_id: 3,
      categoria_id: 3,
      classificacao_id: 2,
      capacidade: 5,
      portais: 4,
      estado: 'São Paulo',
      uf: 'SP',
      tipo_placa_id: 2,
      placa: 'DEF5D54',
      renavam: '00540000054',
      chassi: '9BWZZZ54ZXT054054',
      revisao_km: 19000,
      combustivel_id: 4,
      descricao: 'SUV para transporte de executivos.',
      usuario_id: 1,
    },
    {
      id: 55,
      criado_em: new Date(),
      identificador: 'VEI-055',
      companhia_id: 1,
      status: 'pendente',
      modelo: 'Toro Freedom',
      ano: 2020,
      marca_id: 1,
      categoria_id: 4,
      classificacao_id: 2,
      capacidade: 5,
      portais: 4,
      estado: 'Goiás',
      uf: 'GO',
      tipo_placa_id: 2,
      placa: 'EFG5E55',
      renavam: '00550000055',
      chassi: '9BWZZZ55ZXT055055',
      revisao_km: 26000,
      combustivel_id: 3,
      descricao: 'Pickup média para transporte de equipamentos.',
      usuario_id: 2,
    },
    {
      id: 56,
      criado_em: new Date(),
      identificador: 'VEI-056',
      companhia_id: 2,
      status: 'liberado',
      modelo: 'Spin LS',
      ano: 2019,
      marca_id: 5,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 7,
      portais: 4,
      estado: 'Santa Catarina',
      uf: 'SC',
      tipo_placa_id: 1,
      placa: 'FGH5F56',
      renavam: '00560000056',
      chassi: '9BWZZZ56ZXT056056',
      revisao_km: 49000,
      combustivel_id: 1,
      descricao: 'Van compacta para transporte interno.',
      usuario_id: 3,
    },
    {
      id: 57,
      criado_em: new Date(),
      identificador: 'VEI-057',
      companhia_id: 1,
      status: 'liberado',
      modelo: 'Creta Attitude',
      ano: 2020,
      marca_id: 4,
      categoria_id: 3,
      classificacao_id: 2,
      capacidade: 5,
      portais: 4,
      estado: 'Tocantins',
      uf: 'TO',
      tipo_placa_id: 2,
      placa: 'GHI5G57',
      renavam: '00570000057',
      chassi: '9BWZZZ57ZXT057057',
      revisao_km: 17000,
      combustivel_id: 4,
      descricao: 'SUV intermediário para gerência regional.',
      usuario_id: 1,
    },
    {
      id: 58,
      criado_em: new Date(),
      identificador: 'VEI-058',
      companhia_id: 2,
      status: 'pendente',
      modelo: 'Kwid Zen',
      ano: 2021,
      marca_id: 5,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: 'Roraima',
      uf: 'RR',
      tipo_placa_id: 2,
      placa: 'HIJ5H58',
      renavam: '00580000058',
      chassi: '9BWZZZ58ZXT058058',
      revisao_km: 13000,
      combustivel_id: 1,
      descricao: 'Veículo econômico para pequenos deslocamentos.',
      usuario_id: 2,
    },
    {
      id: 59,
      criado_em: new Date(),
      identificador: 'VEI-059',
      companhia_id: 1,
      status: 'liberado',
      modelo: 'Duster Expression',
      ano: 2018,
      marca_id: 4,
      categoria_id: 3,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: 'Acre',
      uf: 'AC',
      tipo_placa_id: 1,
      placa: 'JKL5I59',
      renavam: '00590000059',
      chassi: '9BWZZZ59ZXT059059',
      revisao_km: 52000,
      combustivel_id: 1,
      descricao: 'SUV para operações de campo.',
      usuario_id: 3,
    },
    {
      id: 60,
      criado_em: new Date(),
      identificador: 'VEI-060',
      companhia_id: 2,
      status: 'cancelado',
      modelo: 'Logan Authentique',
      ano: 2016,
      marca_id: 5,
      categoria_id: 2,
      classificacao_id: 1,
      capacidade: 5,
      portais: 4,
      estado: 'Rondônia',
      uf: 'RO',
      tipo_placa_id: 1,
      placa: 'LMN5J60',
      renavam: '00600000060',
      chassi: '9BWZZZ60ZXT060060',
      revisao_km: 84500,
      combustivel_id: 1,
      descricao: 'Sedan desativado por desgaste excessivo.',
      usuario_id: 1,
    },
  ],
  skipDuplicates: true,
});

console.log('✔️ Veículos 51–60 incluídos.\n');
}

main()
    .then(async () => {
        console.log('\nSeed executado com sucesso!');
        await prisma.$disconnect();
    })
    .catch(async (e) => {
        console.error('Erro no seed:', e);
        await prisma.$disconnect();
        process.exit(1);
    });

